// Runs every demo and writes SHOWCASE.md with the real outputs, so the write-up on the blog
// comes from recorded runs rather than illustrative examples.
//
//   pnpm showcase                                   # replay examples/fixtures/showcase.json (no key needed)
//   JUDGMENT_FIXTURES=record pnpm showcase          # answer misses live and update the fixture file
//   JUDGMENT_FIXTURES=live pnpm showcase            # everything live, fixtures untouched
//   SHOWCASE_OUTPUT=/tmp/x.md pnpm showcase         # write somewhere else (CI replay check)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { JudgmentClient, MemoryCache, calibrate, judgeFromEnv, noul, renderCalibration } from "@overclock/judgment-core";
import { contracts } from "./demos/contracts.js";
import { guardLlmOutput } from "./demos/guard-llm-output.js";
import { supportTickets } from "./demos/support-tickets.js";
import { validateUgc } from "./demos/validate-ugc.js";
import type { Demo, DemoReport } from "./demos/types.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = join(here, "fixtures", "showcase.json");
const output = process.env.SHOWCASE_OUTPUT ?? join(here, "SHOWCASE.md");
const mode = (process.env.JUDGMENT_FIXTURES as "replay" | "record" | "live" | undefined) ?? "replay";

interface Timing {
  demo: string;
  ms: number;
  requests: number;
  questions: number;
  cacheHits: number;
  inputTokens: number;
  outputTokens: number;
}

async function runDemo(demo: Demo, name: string, timings: Timing[]): Promise<DemoReport> {
  const judge = judgeFromEnv({ fixtures });
  const client = new JudgmentClient({ judge, cache: new MemoryCache() });
  const started = performance.now();
  const report = await demo(client);
  const usage = report.usage ?? client.usage();
  timings.push({ demo: name, ms: performance.now() - started, requests: usage.requests, questions: usage.questions, cacheHits: usage.cacheHits, inputTokens: usage.inputTokens, outputTokens: usage.outputTokens });
  return report;
}

async function calibrationSection(timings: Timing[]): Promise<DemoReport> {
  const lines = readFileSync(join(here, "data", "polite.jsonl"), "utf8").split("\n").filter(Boolean);
  const cases = lines.map((line) => JSON.parse(line) as { value: string; label: boolean });
  const client = new JudgmentClient({ judge: judgeFromEnv({ fixtures }) });
  const question = noul("is polite and professional");
  const started = performance.now();
  const judgments = await Promise.all(cases.map((c) => client.ask(c.value, question)));
  timings.push({ demo: "calibrate", ms: performance.now() - started, ...client.usage() });
  const items = cases.map((c, i) => ({ p: judgments[i]!.p, label: c.label }));
  const report = calibrate(items, { metric: "f1" });
  const rows = cases.map((c, i) => `| ${c.value.replace(/\|/g, "\\|")} | ${c.label ? "polite" : "not polite"} | ${(items[i]!.p * 100).toFixed(0)}% |`);
  return {
    id: "calibrate",
    title: "Pick the threshold from data",
    summary: `${cases.length} labeled messages judged for "is polite and professional". The calibrate CLI turns the probabilities into an operating point instead of a guess.`,
    sections: [
      { heading: "Command", body: "```sh\nsemantic-types calibrate examples/data/polite.jsonl --predicate \"is polite and professional\"\n```" },
      { heading: "Report", body: "```text\n" + renderCalibration(report) + "\n```\n\nRecommended: `s.is(\"is polite and professional\", { threshold: " + report.best.threshold.toFixed(2) + " })`." },
      { heading: "Labeled set", body: ["| message | label | p |", "| --- | --- | --- |", ...rows].join("\n") },
    ],
  };
}

function render(reports: DemoReport[], timings: Timing[]): string {
  const live = mode !== "replay";
  const parts: string[] = [];
  parts.push("# Showcase: recorded runs");
  parts.push("");
  parts.push(
    `Generated by \`pnpm showcase\` on ${new Date().toISOString().slice(0, 10)} in **${mode}** mode. ` +
      (live
        ? "Every number below comes from live TypeSafe (Jev) responses, recorded into `examples/fixtures/showcase.json`."
        : "Answers replayed from `examples/fixtures/showcase.json`, which was recorded from live TypeSafe (Jev) responses; request counts are real, token counts are only present in recorded runs."),
  );
  parts.push("");
  parts.push("| demo | wall time | requests | questions | cache hits | tokens in / out |");
  parts.push("| --- | --- | --- | --- | --- | --- |");
  for (const t of timings) {
    parts.push(`| ${t.demo} | ${(t.ms / 1000).toFixed(2)} s | ${t.requests} | ${t.questions} | ${t.cacheHits} | ${t.inputTokens} / ${t.outputTokens} |`);
  }
  parts.push("");
  for (const report of reports) {
    parts.push(`## ${report.title}`);
    parts.push("");
    parts.push(report.summary);
    parts.push("");
    for (const section of report.sections) {
      parts.push(`### ${section.heading}`);
      parts.push("");
      parts.push(section.body);
      parts.push("");
    }
  }
  parts.push("---");
  parts.push("");
  parts.push("Each table is one recorded run on the inputs shown, judged by `jev-latest`. Probabilities are the model's, thresholds are the schema's. Change either and the outcomes move; that is the point of keeping the evidence.");
  return `${parts.join("\n")}\n`;
}

async function main(): Promise<void> {
  if (mode === "replay" && !existsSync(fixtures)) {
    console.error(`no fixture file at ${fixtures}; run with JUDGMENT_FIXTURES=record and TYPESAFE_API_KEY first`);
    process.exit(2);
  }
  const timings: Timing[] = [];
  const reports: DemoReport[] = [];
  reports.push(await runDemo(guardLlmOutput, "guard-llm-output", timings));
  reports.push(await runDemo(validateUgc, "validate-ugc", timings));
  reports.push(await runDemo(contracts, "contracts", timings));
  reports.push(await calibrationSection(timings));
  reports.push(await runDemo(supportTickets, "support-tickets", timings));
  writeFileSync(output, render(reports, timings));
  console.log(`wrote ${output} (${mode})`);
  for (const t of timings) console.log(`  ${t.demo}: ${t.requests} requests, ${t.questions} questions, ${(t.ms / 1000).toFixed(2)} s`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
